version: '3'

services:
  consul:
    image: consul:1.8.0
    ports:
      - 8500:8500   # HTTP API
      - 8300:8300   # Server RPC
      - 8301:8301   # Serf LAN
      - 8302:8302   # Serf WAN
      - 8600:8600   # DNS Interface
  essample-cassandra-node:
    image: cassandra:3.11.7
    environment:
      - CASSANDRA_SEEDS=essample-cassandra
  essample--cassandra-migration:
    extends:
      file: cassandra-migration.yml
      service: essample-cassandra-migration
    environment:
      - CREATE_KEYSPACE_SCRIPT=create-keyspace.cql
